name = "medium_01"
compatibility_date = "2024-08-21"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYjE0MzRjNGEtMDkyMS00NGY2LTkyMjUtZmU4OTZjOGEwMmRlIiwidGVuYW50X2lkIjoiZjY3OGZjMjM0OTU1YzE4Yzg3NWU2Mzk1MTg2ZTNiYmQyZDM0OWFkZjAxNDMwNGViYTExY2E3NWRmNTM1MjZjZiIsImludGVybmFsX3NlY3JldCI6IjgwYzZjMDVlLTI0OTktNDc1YS1iNjJkLTk3YjEyNmE5ZTE1ZiJ9.Hw7Cl4RumGxiNjpMpD3rU0LqVuCf8NJvtjslPdIBMjs"
JWT_SECRET="asssd"